name: Deploy to Firebase

on:
  push:
    branches:
      - snehashish

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FIREBASE_PROJECT_ID: devops-cbd3375
      FIREBASE_TOKEN: 1//05Pd7CX86lDq0CgYIARAAGAUSNwF-L9IrrBFFbenyaplzT9uYTZcqpyJzH2v1Gec0NIJ0XO5sSSujfbdmyKIMptFTABSsRhoaTxo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          CI=false
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      FIREBASE_PROJECT_ID: devops-cbd3375
      FIREBASE_KEY: 1//05Pd7CX86lDq0CgYIARAAGAUSNwF-L9IrrBFFbenyaplzT9uYTZcqpyJzH2v1Gec0NIJ0XO5sSSujfbdmyKIMptFTABSsRhoaTxo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'
       
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: $FIREBASE_KEY
